@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jun 05 22:59:42 +0800 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim final_testbench_behav -key {Behavioral:sim_1:Functional:final_testbench} -tclbatch final_testbench.tcl -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/Simulation Sources/testbench_2_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/Simulation Sources/testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/sll_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/sb_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/ble_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/li_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/zfr_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/final_testbench_behav.wcfg -log simulate.log"
call xsim  final_testbench_behav -key {Behavioral:sim_1:Functional:final_testbench} -tclbatch final_testbench.tcl -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/Simulation Sources/testbench_2_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/Simulation Sources/testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/sll_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/sb_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/ble_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/li_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/zfr_testbench_behav.wcfg -view C:/Users/loloh/OneDrive - up.edu.ph/Desktop/UPD2.2S Catalogue/UPD2.2S/CS 21 - Computer Organization and Architecture/Project 2 v2/CS21_Project2_v2/final_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
